print("Numele, Prenumele: Cebotari Anastasia")
print("Data, Luna, Anul Nașterii: 23. 05.2005")
print("Locul Nașterii: mun.Bălți, Republica Moldova")
print("Domiciliul: str. Mihail Lesecico 16")
print("Numărul de telefon: 079098598")
print("Școala: Instituția Publică Liceul Teoretic Mihai Eminescu, clasa a 10 a")
print("Studii: 2015-2020 gimnaziu IPLT Mihai Eminescu, 2011-2015 școala primară IPLT Mihai Eminescu, 2011-2019 Școala de muzică ")
print("Abilități: nivel A3- limba engleză, nivel B1- limba franceză")              
print("Operare la calculator în aplicațiile: Microsoft Word, Microsoft Excel, Microsoft Power Point, PASCAL, PYTHON, Visual Studio")
print("Hobby: mă ocup cu limbile străine, sport, cântatul, cititul")
print("Recomandări, referințe: Ana Saranciuc- dirigintă în gimnaziu")
print("Semnatura: CAnastasia")
print("Data: 15.09.2020")